### ISSUE TITLE
pdo_mysql

### ISSUE THREAD

**Issue by carlituxman** [christopherarter/laravel-docker-production#1]
Hi, great job.

I need add php8-pdo_mysql 

This docker-compose.yml simple file to use your dockerfile:

```
version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: my-app/app
        ports:
            - '${APP_PORT:-80}:8080'
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
```
